# Generated by Django 5.1.6 on 2025-03-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingoboarditem',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bingoboarditem',
            name='suggested_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
