# Generated by Django 5.1.6 on 2025-03-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_bingoboarditem_suggested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingogame',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
