# Generated by Django 5.1.6 on 2025-03-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_bingogame_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingogame',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
