# Generated by Django 5.1.6 on 2025-03-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_bingogame_is_private'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_player_name_per_game',
        ),
    ]
