# Generated by Django 6.0.2 on 2026-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingogame',
            name='is_spectateable',
            field=models.BooleanField(default=False),
        ),
    ]
