# Generated by Django 5.1.6 on 2025-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_gameevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingogame',
            name='board_size',
            field=models.IntegerField(choices=[(4, '4x4'), (5, '5x5')], default=5),
        ),
        migrations.AddField(
            model_name='bingogame',
            name='win_condition',
            field=models.CharField(choices=[('traditional', 'Traditional (line)'), ('all', 'All Squares')], default='traditional', max_length=20),
        ),
    ]
