# Generated by Django 5.1.6 on 2025-02-23 15:25

from django.db import migrations



def set_default_game_variations(apps, schema_editor):
    # Get the historical version of the model
    BingoGame = apps.get_model('bingo', 'BingoGame')
    
    # Update all existing games
    BingoGame.objects.update(
        board_size=5,
        win_condition='traditional'
    )

def reverse_game_variations(apps, schema_editor):
    # No need to reverse this operation
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_bingogame_board_size_bingogame_win_condition'),
    ]

    operations = [
        migrations.RunPython(
            set_default_game_variations,
            reverse_game_variations
        )
    ]
